version: "3.7"
services:
  web:
    build: .
    volumes:
      - ./site:/var/www/html
    ports: 
      - 8080:80
    depends_on:
      - db
  db:
    build: ./Database
    container_name: database
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"